name: triggered-workflow

on:
  repository_dispatch:
    types: [do-stuff, do-other-stuff]
    client_payload:
      EMAIL:
      INITIATOR:
      TICKET:
  workflow_dispatch:

jobs:
  do-stuff:
    # if: ${{ github.event.action == 'do-stuff' || github.event.action == 'do-other-stuff' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "other steps here"
        env:
          TICKET: "${{ github.event.client_payload.TICKET }}"
          INITIATOR: "${{ github.event.client_payload.INITIATOR }}"
          EMAIL: "${{ github.event.client_payload.EMAIL }}"




  grafana-annotate:
    needs: do-stuff
    if: always()
    uses: dsmith73/testrepo/.github/workflows/grafana-annotation-workflow.yml@main
    with:
      event_type: triggered-workflow
    secrets:
      LOKI_SECRET_JSON: ${{ secrets.LOKI_SECRET_JSON }}
    
          
