name: triggered-workflow

on:
  repository_dispatch:
  # Called from an external source / application / product  
    types: [do-stuff, do-other-stuff]
  workflow_dispatch:
  # Direct execution from GUI or call from another workflow or automation in GitHub  
    inputs:
      TICKET:
        description: 'Ticket Number'
        required: false
      EMAIL:
        description: 'User Email'
        required: false


jobs:
  do-stuff:
    if: |
      github.event_name == 'workflow_dispatch' || 
      github.event.action == 'do-stuff' || 
      github.event.action == 'do-other-stuff'
    runs-on: ubuntu-latest
    steps:
      - run: echo "other steps here"
        env:
          TICKET: "${{ github.event.client_payload.TICKET || inputs.TICKET }}"
          EMAIL: "${{ github.event.client_payload.EMAIL || inputs.EMAIL }}"
          INITIATOR: "${{ github.event.client_payload.INITIATOR || github.actor }}"




  grafana-annotate:
    needs: do-stuff
    if: always()
    uses: dsmith73/testrepo/.github/workflows/grafana-annotation-workflow.yml@main
    with:
      event_type: triggered-workflow
    secrets:
      LOKI_SECRET_JSON: ${{ secrets.LOKI_SECRET_JSON }}
    
          
